#!/usr/bin/env zsh
if [ -z ${prompt_color} ];then
  prompt_color='yellow'
fi
if [ -z ${prompt_name} ];then
  prompt_name='%m'
fi

PROMPT="%F{9}@%f%F{${prompt_color}}${prompt_name}%f %F{30}>>%f "
PROMPT2="%F{blue}%_> %f"
SPROMPT='correct: %F{red}'%R'%f to %F{blue}'%r'%f [y,n,a,e]? %f'

ZSH_GIT_PROMPT_DIR=$HOME/.zsh/zsh-git-prompt;
if [ ! -e "$ZSH_GIT_PROMPT_DIR" ];then
  git clone git@github.com:olivierverdier/zsh-git-prompt.git $ZSH_GIT_PROMPT_DIR
fi
source $ZSH_GIT_PROMPT_DIR/zshrc.sh
RPROMPT='%F{30}[%f$(git_super_status)%F{30}%~]%f'
