#[[plugins]]
#repo = 'nise-nabe/unite-openpne'

[[plugins]]
repo = 'superbrothers/vim-vimperator'
on_ft = 'vimperator'

[[plugins]]
repo = 'Simple-Javascript-Indenter'
on_ft = 'javascript'

[[plugins]]
repo = 'evidens/vim-twig'
on_ft = 'twig'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'eruby']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = 'crystal'

#[[plugins]]
#repo = 'Shougo/neosnippet'
#insert = 1

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'supermomonga/neocomplete-rsense.vim'
#on_ft = 'ruby'

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = ['Gista']
on_func = 'gista#'
