[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

#[[plugins]]
#repo = 'sudo.vim'

[[plugins]]
repo = 'vim-scripts/vimwiki'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'yuratomo/w3m.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

#[[plugins]]
#repo = 'project.tar.gz'

[[plugins]]
repo = 'tpope/vim-endwise'


#[[plugins]]
#repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'kien/ctrlp.vim'

#[[plugins]]
#repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'embear/vim-localvimrc'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'basyura/TweetVim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'yuratomo/gmail.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'rbtnn/vimconsole.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'itchyny/lightline.vim'

#[[plugins]]
#repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/dictionary.vim'

[[plugins]]
repo = 'mattn/vimplenote-vim'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

#[[plugins]]
#repo = 'tomasr/molokai'
#repo = 'altercation/vim-colors-solarized'
