"set guifont=12
set guifont=Ricty:h18
"" スクロールバー非表示
"set guioptions-=r
"set guioptions-=l
"set guioptions-=b
"" ツールバー非表示
"set guioptions-=T
set guioptions=c
"set guioptions-=e
"set guioptions=i
colorscheme mycolor
set guicursor=a:blinkon0
set title
set transparency=7
" 常にタブを表示
set showtabline=2
set lines=150 columns=330

set fuoptions=maxvert,maxhorz
au GUIEnter * set fullscreen
map ,m :set guioptions=m<CR>
map ,n :set guioptions-=m<CR>
noremap! ¥ \
noremap! \ ¥

nnoremap b :buffer<SPACE>
nnoremap <C-f>c :tabnew \| :VimShellCreate<CR>
nnoremap <C-f>n :tabnext<CR>
nnoremap <C-f>p :tabprevious<CR>
inoremap <C-f>c <ESC>:tabnew \| :VimShellCreate<CR>
inoremap <C-f>n <ESC>:tabnext<CR>
inoremap <C-f>p <ESC>:tabprevious<CR>

"起動時にvimshell
if !argc()
    autocmd vimenter * VimShell
endif
if filereadable(expand('~/.vim/gvimlocalrc'))
  source ~/.vim/gvimlocalrc
endif
