"set guifont=12
set guifont=Ricty:h16
"" スクロールバー非表示
"set guioptions-=r
"set guioptions-=l
"set guioptions-=b
"" ツールバー非表示
"set guioptions-=T
set guioptions=c
"set guioptions-=e
"set guioptions=i
colorscheme mycolor
set guicursor=a:blinkon0
set title
"set transparency=7
" 常にタブを表示
set showtabline=2
set lines=150 columns=330

set fuoptions=maxvert,maxhorz
au GUIEnter * set fullscreen
map ,m :set guioptions=m<CR>
map ,n :set guioptions-=m<CR>
inoremap! \ \
cnoremap! \ \
