#[[plugins]]
#repository = 'nise-nabe/unite-openpne'

[[plugins]]
repository = 'superbrothers/vim-vimperator'
filetypes = 'vimperator'

[[plugins]]
repository = 'Simple-Javascript-Indenter'
filetypes = 'javascript'

[[plugins]]
repository = 'evidens/vim-twig'
filetypes = 'twig'

[[plugins]]
repository = 'slim-template/vim-slim'
filetypes = 'slim'

[[plugins]]
repository = 'kchmck/vim-coffee-script'
filetypes = 'coffee'

[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'

[[plugins]]
repository = 'mattn/emmet-vim'
filetypes = ['html', 'php', 'eruby']

[[plugins]]
repository = 'plasticboy/vim-markdown'
filetypes = ['markdown']

[[plugins]]
repository = 'rhysd/vim-crystal'
filetypes = 'crystal'

[[plugins]]
repository = 'supermomonga/neocomplete-rsense'
filetypes = 'ruby'
