[[plugins]]
repository = 'sudo.vim'

[[plugins]]
repository = 'vimwiki'

[[plugins]]
repository = 'Shougo/neocomplete'

[[plugins]]
repository = 'Shougo/unite.vim'

[[plugins]]
repository = 'Shougo/vimfiler'

[[plugins]]
repository = 'Shougo/vimproc'

  [plugins.build]
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'

[[plugins]]
repository = 'Shougo/vimshell'

[[plugins]]
repository = 'thinca/vim-ref'

[[plugins]]
repository = 'yuratomo/w3m.vim'

[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'mattn/webapi-vim'

[[plugins]]
repository = 'h1mesuke/unite-outline'

[[plugins]]
repository = 'tpope/vim-surround'

[[plugins]]
repository = 'tpope/vim-fugitive'

[[plugins]]
repository = 'project.tar.gz'

[[plugins]]
repository = 'rking/ag.vim'

[[plugins]]
repository = 'tpope/vim-endwise'

[[plugins]]
repository = 'tpope/vim-rails'

[[plugins]]
repository = 'soramugi/auto-ctags.vim'

[[plugins]]
repository = 'Shougo/neomru.vim'

[[plugins]]
repository = 'kien/ctrlp.vim'

[[plugins]]
repository = 'scrooloose/nerdtree'

[[plugins]]
repository = 'mrtazz/simplenote.vim'

[[plugins]]
repository = 'embear/vim-localvimrc'

[[plugins]]
repository = 'vim-jp/vital.vim'

[[plugins]]
repository = 'haya14busa/incsearch.vim'

[[plugins]]
repository = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repository = 'basyura/TweetVim'

[[plugins]]
repository = 'basyura/twibill.vim'

[[plugins]]
repository = 'tyru/open-browser.vim'

[[plugins]]
repository = 'yuratomo/gmail.vim'

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'thinca/vim-quickrun'

[[plugins]]
repository = 'taglist.vim'

[[plugins]]
repository = 'rbtnn/vimconsole.vim'

[[plugins]]
repository = 'kmnk/vim-unite-giti'

[[plugins]]
repository = 'vim-jp/vimdoc-ja'

[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'nanotech/jellybeans.vim'

[[plugins]]
repository = 'Shougo/neosnippet'

[[plugins]]
repository = 'Shougo/neosnippet-snippets'

[[plugins]]
repository = 'itchyny/dictionary.vim'