#!/usr/bin/env zsh

function loadPlugins() {
  local zsh_plugin_dir=${ZSH_HOME}'/plugins/'
  local self=${ZSH_HOME}/plugin_loader
  local -a func_name=($(cat $self | grep -E '[f]unction _zsh_plugin_'| sed -E 's/function (_zsh_plugin_[a-zA-Z_]+)\(\){/\1/g'))

  function _zsh_plugin_load(){
    local plugin_name=$1
    if [ ! `find $zsh_plugin_dir -name "${i}"` ];then plugin_name=$(/bin/ls ${zsh_plugin_dir}|grep ${plugin_name});fi
    #_pluginGetFuncName ${plugin_name}
    if [ -e ${zsh_plugin_dir}${plugin_name} ];then
      source "${zsh_plugin_dir}${plugin_name}"
    fi
  }

  function _zsh_plugin_get_fullpath(){
    find $zsh_plugin_dir -name "${1}"
  }

  function _zsh_plugin_get_names(){
    #プラグイン名を取り出す(プラグイン名として管理)
    /bin/ls ${zsh_plugin_dir} | sed -e 's/.zsh//g'
    #/bin/ls ${zsh_plugin_dir}
  }

  function _zsh_plugin_get_func_name(){
    local plugin_name=$1
    cat ${zsh_plugin_dir}${plugin_name}|grep '( function|\(\) )' |grep -vE '^#'|awk -F'(' '{print $1}'|sed -e "s/function//g"
  }

  function _zsh_plugin_unload(){
    unfunction `_pluginGetFuncNames | grep $1`
  }

  function _zsh_plugin_reload(){
    unloadPlugin $1
  }

  #PLUGIN_NAMES=$(_pluginGetNames)
  for i in $@;do _zsh_plugin_load $i;done
  for i in ${func_name[@]};do unfunction $i;done
}

function _loadPlugins() {
  compadd `/bin/ls $HOME/.zsh/plugins | sed -e 's/.zsh//g'`
}
compdef _loadPlugins loadPlugins
