#!/usr/bin/env zsh

if [ -z "${ZSH_HOME}" ]; then
  ZSH_HOME="${HOME}/.zsh"
else
  ZSH_HOME="${ZSH_HOME%/}"
fi

export ZSH_HOME
export ZSH_PLUGIN_DIR=${ZSH_HOME}/plugins

function plugin() {

  # register plugin as temporary function
  # call plugin name, real path will load and execute
  function _zsh_plugin_register() {
    local plugin_name=$1
    local file=`find $ZSH_PLUGIN_DIR -name ${plugin_name} -type f`
    [ -n "$file" ] && {
      function $plugin_name() {
        unfunction $0
        source ${ZSH_PLUGIN_DIR}/$0 $@
        if which $0 > /dev/null ;then
          $0 $@
        else
          plugin register $0
        fi
      }
    } || return 1
  }

  function _zsh_plugin_call_onload() {
    local plugin=$1
    _zsh_plugin_register $plugin
    [ ! $? = 0 ] && echo "plugin $plugin does not exist." && return 1
    shift
    $plugin $@
  }

  local call=_zsh_plugin_$1
  shift
  $call $@
  unfunction $call
}

function _plugin() {
  local -a completions=(register)
  compadd $completions
}
compdef _plugin plugin
